### ISSUE TITLE
[TopDownCharacter] Add ability to melee via right click for the player.

### ISSUE THREAD

**Issue by ducdao** [ducdao/Dino#16]
Add ability for the player to melee using the right click.

**Comment by ThomasLFranklin** [comment]
I don't think we need to have the player be able to sprint. Between jumping and a ranged weapon, I'm starting to think that if we add sprinting, the game might be too easy, even if it is only a limited ability. That and the animation already looks like he's running lol

**Comment by ducdao** [comment]
Sounds good. I'll change this to melee attack?

**Comment by ducdao** [comment]
Note: When enemy is in range, right clicking to melee will make the LaserGunSound.
