### ISSUE TITLE
[TopDownCharacter] Process Damage Inside Player

### ISSUE THREAD

**Issue by ducdao** [ducdao/Dino#17]
Implement damage processing for player character.

**Comment by ThomasLFranklin** [comment]
Issue #17 and #18 are both going to modify both the enemy characters and the player pawn, so we need to coordinate who is going to implement what when, so that we don't get conflicts.

**Comment by ducdao** [comment]
I can do both of them but I don't want to modify anything in the EnemyBlueprints folder unless I get the okay from you, @ThomasLFranklin. I'll let you know when I want to implement this in the EnemyBlueprints.
