### ISSUE TITLE
[PauseMenu] Quit Button Crashes Game

### ISSUE THREAD

**Issue by ducdao** [ducdao/Dino#23]
Found a bug, @Rivers1717! In the pause menu, the quit button crashes the game.

**Comment by ducdao** [comment]
I think I fixed this. Someone double check.

**Comment by ducdao** [comment]
So, there's a bug where if you play the game, pause, quit, and play the game again, you can't move the character. @Rivers1717, if you have time to work on this bug, please do. I'm gonna move onto something else.

**Comment by ThomasLFranklin** [comment]
Pause menu is gone. Problem solved
